#########################
#	browser		#
########################

windowrulev2 = workspace 1, class:^(firefox)$


#########################
#	electrons	#
#########################

windowrulev2 = workspace 4, class:^(discord)$
exec-once = discord
